# Generated by Django 3.1.1 on 2020-09-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True, default=True, max_length=500)),
                ('url', models.URLField(blank=True, default=None, max_length=250, null=True)),
                ('image', models.ImageField(upload_to=None)),
                ('index', models.PositiveIntegerField()),
                ('tags', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boards.board')),
            ],
        ),
    ]
